---
version: '3.1'

services:
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: change_detection
      POSTGRES_PASSWORD: change_detection
      POSTGRES_DB: change_detection_development
    volumes:
      - ./tmp/postgresql:/var/lib/postgresql
    ports:
      - 5432:5432
  mailcatcher:
    image: sj26/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025
