---
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: change_detection_development
  username: change_detection
  password: change_detection
  host: localhost
  port: 5432
  # schema_search_path: myapp,sharedapp,public
  # min_messages: notice

test:
  <<: *default
  database: change_detection_test
  username: change_detection
  password: change_detection
  host: localhost
  port: 5432

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
